import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/footer";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";

const montserrat = Montserrat({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider session={session}>
          <Navbar />
          <ToastContainer />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
